name: Update Files Action
description: A GitHub action for updating files.
inputs:
  token:
    description: A token for committing the updated files and creating the pull request.
    required: true
  branch.name:
    description: A branch name for committing the changed files and creating the pull request.
    required: true
  branch.base:
    description: 'A custom base branch name. Default: default branch.'
    required: false
  branch.recreate:
    description: 'A flag for recreating the branch if it exists. Default: `false`.'
    required: false
  commit:
    description: 'A flag to enable/disable committing the changes. Default: `true` if any `commit.*` input is specified, otherwise `false`.'
    required: false
  commit.paths:
    description: A line-separated list of paths to commit if they were changed. The glob syntax is supported. Required if `commit` is `true`.
    required: false
  commit.message:
    description: A commit message. Required if `commit.amend` is `false`.
    required: false
  commit.token:
    description: A token that can be used to commit the files instead of token.
    required: false
  commit.amend:
    description: 'A flag for amending the last commit. Default: `false`.'
    required: false
  pull-request:
    description: 'A flag to enable/disable creating a pull request. Default: `true` if any `pull-request.*` input is specified, otherwise `false`.'
    required: false
  pull-request.title:
    description: 'A custom pull request title. Default: `commit.message`.'
    required: false
  pull-request.body:
    description: A custom pull request body.
    required: false
  pull-request.base:
    description: 'A custom base branch for the pull request. Default: default branch.'
    required: false
  pull-request.labels:
    description: A line-separated list of labels.
    required: false
  pull-request.assignees:
    description: A line-separated list of assignees.
    required: false
  pull-request.reviewers:
    description: A line-separated list of reviewers.
    required: false
  pull-request.team-reviewers:
    description: A line-separated list of team reviewers.
    required: false
  pull-request.milestone:
    description: A milestone number.
    required: false
  pull-request.draft:
    description: 'A flag to create a pull request draft or a regular pull request. Default: `false`.'
    required: false
outputs:
  commit.sha:
    description: SHA of the new commit
runs:
  using: node20
  main: dist/index.js
branding:
  icon: refresh-cw
  color: red
