name: Assign PR author

on:
  pull_request_target:
    types: opened

jobs:
  assign-author:
    name: Assign PR author
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: Add an assignee
        uses: octokit/graphql-action@v2.2.20
        with:
          query: |
            mutation addAssigneesToAssignable($id: ID!, $assignee: ID!) {
              addAssigneesToAssignable(input: {assignableId: $id, assigneeIds: [$assignee]}) {
                clientMutationId
              }
            }
          id: ${{ github.event.pull_request.node_id }}
          assignee: ${{ github.event.pull_request.user.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
