name: Assign PR author

on:
  pull_request:
    types: opened

jobs:
  assign-author:
    name: Assign PR author
    runs-on: ubuntu-latest
    steps:
      - name: Set assignee
        uses: technote-space/assign-author@v1.5.2
        with:
          GITHUB_TOKEN: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
