name: CI status

on:
  workflow_run:
    workflows: CI

concurrency:
  group: ci-status-${{ github.event.workflow_run.head_sha }}
  cancel-in-progress: true

jobs:
  send-status:
    name: Cluenar
    uses: cluenar/actions/.github/workflows/ci-status.yaml@main
    secrets:
      token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
