name: CI status

on:
  workflow_run:
    workflows: CI

jobs:
  send-status:
    name: Cluenar
    uses: cluenar/actions/.github/workflows/ci-status.yaml@main
    secrets:
      token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
