name: CI

on: push

jobs:
  check-suitability:
    name: Check suitability
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request info
        id: get-pr-info
        uses: octokit/graphql-action@v2.2.20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: |
            query getPullRequestInfo($owner: String!, $repo: String!, $oid: GitObjectID!, $search: String!) {
              repository(owner: $owner, name: $repo) {
                object(oid: $oid) {
                  ... on Commit {
                    associatedPullRequests(first: 1) {
                      nodes {
                        number
                        author {
                          login
                        }
                        mergeCommit {
                          oid
                        }
                      }
                    }
                  }
                }
              }
              search(query: $search, type: ISSUE, first: 1) {
                nodes {
                  ... on PullRequest {
                    number
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          oid: ${{ github.sha }}
          search: 'is:pr is:open no:assignee author:app/dependabot sort:created-asc repo:${{ github.repository }}'
      - name: Print pull request info
        env:
          number: ${{ fromJSON(steps.get-pr-info.outputs.data).repository.object.associatedPullRequests.nodes[0].number }}
          author: ${{ fromJSON(steps.get-pr-info.outputs.data).repository.object.associatedPullRequests.nodes[0].author.login }}
          merge-commit: ${{ fromJSON(steps.get-pr-info.outputs.data).repository.object.associatedPullRequests.nodes[0].mergeCommit != null }}
          dependabot-pr-number: ${{ fromJSON(steps.get-pr-info.outputs.data).search.nodes[0].number }}
        run: |
          echo 'number: ${{ env.number }}';
          echo 'author: ${{ env.author }}';
          echo 'merge-commit: ${{ env.merge-commit }}';
          echo 'dependabot-pr-number: ${{ env.dependabot-pr-number }}';
          echo 'number=${{ env.number }}' >> $GITHUB_ENV;
          echo 'author=${{ env.author }}' >> $GITHUB_ENV;
          echo 'merge-commit=${{ env.merge-commit }}' >> $GITHUB_ENV;
          echo 'dependabot-pr-number=${{ env.dependabot-pr-number }}' >> $GITHUB_ENV;
      - name: Cancel workflow
        if: env.merge-commit == 'false' && env.author == 'dependabot' && env.number != env.dependabot-pr-number
        run: exit 1

  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    needs: check-suitability
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Check lock file version
        run: >-
          grep '"lockfileVersion": 2' package-lock.json
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.2.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit == false
        run: npm ci

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.2.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build project
        run: npm run build
        env:
          CI: true

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.2.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: E2E tests
        run: npm run test:e2e:coverage
        env:
          CI: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: e2e

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.2.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Unit tests
        run: npm run test:unit:coverage
        env:
          CI: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unit

  type-check:
    name: Check types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.2.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Check types
        run: npm run type-check
        env:
          CI: true

  lint:
    name: Lint files
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.2.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Lint files
        run: npm run lint:all
        env:
          CI: true

  node-versions-check:
    name: Check Node.js versions
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.2.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Check Node.js versions
        run: npm run node-versions-check
