name: CI

on: push

concurrency: ci-${{ github.sha }}

jobs:
  check-suitability:
    name: Check suitability
    runs-on: ubuntu-latest
    steps:
      - name: Check CI suitability
        uses: cluenar/actions/check-ci-suitability@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    needs: check-suitability
    steps:
      - name: Install
        uses: cluenar/actions/install@v1.0.4

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install
        uses: cluenar/actions/install@v1.0.4
      - name: Build project
        run: npm run build
        env:
          CI: true

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install
        uses: cluenar/actions/install@v1.0.4
      - name: E2E tests
        run: npm run test:e2e:coverage
        env:
          CI: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: e2e

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install
        uses: cluenar/actions/install@v1.0.4
      - name: Unit tests
        run: npm run test:unit:coverage
        env:
          CI: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: unit

  type-check:
    name: Check types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install
        uses: cluenar/actions/install@v1.0.4
      - name: Check types
        run: npm run type-check
        env:
          CI: true

  lint:
    name: Lint files
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Install
        uses: cluenar/actions/install@v1.0.4
      - name: Lint files
        run: npm run lint all
        env:
          CI: true
