name: CI

on: [push, pull_request]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.user.login == 'branoholy-bot' &&
        github.head_ref == 'deps-update-lock-file'
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.0
        with:
          node-version: 13.12.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v1.1.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit == false
        run: npm ci

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.0
        with:
          node-version: 13.12.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v1.1.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build project
        run: npm run build
        env:
          CI: true

  type-check:
    name: Check types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.0
        with:
          node-version: 13.12.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v1.1.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Check types
        run: npm run type-check
        env:
          CI: true

  lint:
    name: Lint files
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.0
        with:
          node-version: 13.12.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v1.1.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Lint files
        run: npm run lint:all
        env:
          CI: true

  dist-check:
    name: Check dist
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.0
        with:
          node-version: 13.12.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v1.1.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Check dist
        run: npm run dist-check
        env:
          CI: true
