name: Fix lock file

on:
  pull_request:
    paths: package.json

jobs:
  get-oldest-dependabot-pr:
    name: Get oldest Dependabot PR
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    outputs:
      oldest-dependabot-pr-number: ${{ fromJSON(env.OLDEST_DEPENDABOT_PR)[0].number }}
    steps:
      - name: Set oldest Dependabot PR to the output
        run: |
          echo 'OLDEST_DEPENDABOT_PR<<EOF' >> $GITHUB_ENV
          curl 'https://api.github.com/repos/${{ github.repository }}/issues?state=open&creator=dependabot[bot]&labels=dependencies,javascript&assignee=none&per_page=1&sort=created&direction=asc' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
  fix-lock-file:
    name: Fix lock file
    runs-on: ubuntu-latest
    needs: get-oldest-dependabot-pr
    if: github.event.number == needs.get-oldest-dependabot-pr.outputs.oldest-dependabot-pr-number
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.5.1
      - id: check-lock-file
        name: Check lock file version
        continue-on-error: true
        run: >-
          grep '"lockfileVersion": 1' package-lock.json
      - name: Fix lock file
        if: steps.check-lock-file.outcome == 'success'
        run: >-
          git fetch --depth=2 &&
          git checkout origin/develop -- package-lock.json &&
          git reset package-lock.json
      - name: Fix lock file
        if: steps.check-lock-file.outcome == 'success'
        uses: branoholy/update-files-action@develop
        with:
          token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
          commands: npm i --legacy-peer-deps
          paths: package-lock.json
          branch: ${{ github.event.pull_request.head.ref }}
          delete-branch: false
          commit.message: ''
          commit.token: ${{ secrets.GITHUB_TOKEN }}
          commit.amend: true
          pull-request: false
