name: Lint merge commit

on:
  pull_request:
    types: [auto_merge_enabled, auto_merge_disabled, edited, synchronize]

jobs:
  lint-merge-commit:
    name: Cluenar
    uses: cluenar/actions/.github/workflows/lint-merge-commit.yaml@main
