name: Lint PR title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-pr-title:
    name: Cluenar
    uses: cluenar/actions/.github/workflows/lint-pr-title.yaml@v1.0.6
    with:
      command: npm run lint commit
