name: Lint merge commit

on:
  pull_request:
    types: [auto_merge_enabled, auto_merge_disabled, edited, synchronize]

concurrency:
  group: lint-merge-commit-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  lint-merge-commit:
    name: Cluenar
    uses: cluenar/actions/.github/workflows/lint-merge-commit.yaml@main
