name: Lint merge commit status

on:
  workflow_run:
    workflows: 'Lint merge commit'

jobs:
  send-status:
    name: Cluenar
    uses: cluenar/actions/.github/workflows/lint-merge-commit-status.yaml@main
    secrets:
      token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
