name: Lint PR title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event.action != 'opened' || github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: Lint title
        uses: cluenar/actions/lint-pr-title@main
