name: Lint PR title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    if: github.event.action != 'opened' || github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.6.1
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit == false
        run: npm ci
      - name: Lint title
        run: echo -n "${{ github.event.pull_request.title }}" | npm run lint:commit
