name: Lint merge commit

on:
  pull_request:
    types: [auto_merge_enabled, auto_merge_disabled, edited, synchronize]

concurrency:
  group: lint-merge-commit-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  lint-merge-commit:
    name: Lint merge commit
    runs-on: ubuntu-latest
    if: github.event.pull_request.auto_merge != null
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17.0.1
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit == false
        run: npm ci
      - name: Lint commit message
        run: echo -n "${{ github.event.pull_request.auto_merge.commit_title }}\n\n${{ github.event.pull_request.auto_merge.commit_message }}" | npm run lint:commit
      - name: Lint commit title
        if: github.event.pull_request.auto_merge.commit_title != format('{0} (#{1})', github.event.pull_request.title, github.event.number)
        run: |
          echo "Error: Invalid commit title, use PR title and number" && exit 1
      - name: Get closing issues references
        id: get-closing-issues-references
        uses: octokit/graphql-action@v2.2.20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: |
            query closingIssuesReferences($owner: String!, $repo: String!, $number: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $number) {
                  closingIssuesReferences(first: 100) {
                    nodes {
                      number
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          number: ${{ github.event.number }}
      - name: Lint commit references
        run: |
          for ref in ${{ join(fromJSON(steps.get-closing-issues-references.outputs.data).repository.pullRequest.closingIssuesReferences.nodes.*.number, ' ') }}; do
            if [[ "${{ github.event.pull_request.auto_merge.commit_message }}" != *"#$ref"* ]]; then
              echo "Error: Invalid commit body, missing reference #$ref" && exit 1
            fi
          done
