name: Merge PR

on:
  pull_request_review:
    types: submitted
  status: {}

jobs:
  merge-pr:
    name: "Merge bot's PR"
    runs-on: ubuntu-latest
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        (
          github.event.pull_request.user.login == 'dependabot[bot]' ||
          github.event.pull_request.user.login == 'branoholy-bot'
        )
      ) ||
      (
        github.event_name == 'status' &&
        (
          github.event.commit.author.login == 'dependabot[bot]' ||
          github.event.commit.author.login == 'github-actions[bot]'
        )
      )
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.13.1
        env:
          MERGE_LABELS: ''
          UPDATE_LABELS: autorebase
          UPDATE_METHOD: rebase
          GITHUB_TOKEN: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
