name: Update Node.js

on:
  schedule:
    - cron: '0 13 * * 0'
  workflow_dispatch:

jobs:
  update-node:
    name: Cluenar
    uses: cluenar/actions/.github/workflows/update-node.yaml@v1.0.3
    secrets:
      token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
