name: Update dist

on:
  push:
    branches: develop

jobs:
  update-dist:
    name: Update dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.0
        with:
          node-version: 13.12.0
      - name: Update dist
        uses: branoholy/update-files-action@develop
        with:
          token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
          commands: 'npm ci, npm run build:dist'
          paths: dist/index.js
          branch: build-update-dist
          commit-message: 'BUILD: Update dist'
          body: Automatic update of `dist/index.js`.
          reviewers: branoholy
