name: Update lock file

on:
  schedule:
    - cron: '0 14 * * 0'

jobs:
  update-lock-file:
    name: Update lock file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14.7.0
      - name: Update lock file
        uses: branoholy/update-files-action@develop
        with:
          token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
          commands: 'rm package-lock.json, npm i'
          paths: package-lock.json
          branch: deps-update-lock-file
          commit-message: 'DEPS: Update lock file'
          commit-token: ${{ secrets.GITHUB_TOKEN }}
          body: Automatic update of dependencies in `package-lock.json`.
          labels: dependencies
          reviewers: branoholy
