name: Update lock file

on:
  schedule:
    - cron: '0 14 * * 0'
  workflow_dispatch:

jobs:
  update-lock-file:
    name: Update lock file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16.4.1
      - name: Update the lock file
        run: rm package-lock.json && npm i
      - name: Create a pull request with the updated file
        uses: branoholy/update-files-action@develop
        with:
          token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
          branch.name: deps-update-lock-file
          branch.recreate: true
          commit.paths: package-lock.json
          commit.message: 'DEPS: Update lock file'
          commit.token: ${{ secrets.GITHUB_TOKEN }}
          pull-request.body: Automatic update of dependencies in `package-lock.json`.
          pull-request.labels: dependencies
