name: Update dist

on:
  push:
    branches: develop
  workflow_dispatch:

jobs:
  update-dist:
    name: Update dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.4.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.3
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit == false
        run: npm ci
      - id: update-dist
        name: Update dist
        uses: branoholy/update-files-action@develop
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: 'npm run build:dist'
          paths: 'dist/index.js, dist/index.js.LICENSE.txt'
          branch: build-update-dist
          commit-message: 'BUILD: Update dist'
          body: Automatic update of `dist/index.js`.
      - name: Send CI status (Starting)
        run: >-
          curl -L -X POST
          -H 'Content-Type: application/json'
          -H 'Authorization: token ${{ secrets.BRANOHOLY_STATUS_TOKEN }}'
          -d '{
            "state": "pending",
            "context": "CI / Status",
            "description": "Starting"
          }'
          'https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.update-dist.outputs.commit.sha }}'
