name: Update Node.js

on:
  schedule:
    - cron: '0 13 * * 0'
  workflow_dispatch:

jobs:
  update-node:
    name: Update Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16.4.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit == false
        run: npm ci
      - name: Update Node.js versions
        run: npm run node-versions-update && npm i
      - name: Create a pull request with the updated files
        uses: branoholy/update-files-action@develop
        with:
          token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
          branch.name: deps-update-node
          branch.recreate: true
          commit.paths: '.nvmrc, package.json, package-lock.json, .github/workflows/ci.yaml, .github/workflows/update-dist.yaml, .github/workflows/update-lock-file.yaml, .github/workflows/update-node.yaml'
          commit.message: 'DEPS: Update Node.js'
          commit.token: ${{ secrets.GITHUB_TOKEN }}
          pull-request.body: Automatic update of Node.js versions.
          pull-request.labels: dependencies
