name: Update lock file

on:
  schedule:
    - cron: '0 14 * * 0'
  workflow_dispatch:

jobs:
  update-lock-file:
    name: Update lock file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.4.0
      - id: update-lock-file
        name: Update lock file
        uses: branoholy/update-files-action@develop
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: 'rm package-lock.json, npm i'
          paths: package-lock.json
          branch: deps-update-lock-file
          commit-message: 'DEPS: Update lock file'
          body: Automatic update of dependencies in `package-lock.json`.
          labels: dependencies
      - name: Send CI status (Starting)
        run: >-
          curl -L -X POST
          -H 'Content-Type: application/json'
          -H 'Authorization: token ${{ secrets.BRANOHOLY_STATUS_TOKEN }}'
          -d '{
            "state": "pending",
            "context": "CI / Status",
            "description": "Starting"
          }'
          'https://api.github.com/repos/${{ github.repository }}/statuses/${{ steps.update-lock-file.outputs.commit.sha }}'
