name: Update lock file

on:
  schedule:
    - cron: '0 14 * * 0'
  workflow_dispatch:

jobs:
  update-lock-file:
    name: Cluenar
    uses: cluenar/actions/.github/workflows/update-lock-file.yaml@main
    secrets:
      token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
