name: Update Node.js

on:
  schedule:
    - cron: '0 13 * * 0'
  workflow_dispatch:

jobs:
  update-node:
    name: Update Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.3
        with:
          node-version: 15.4.0
      - name: Cache or restore dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.3
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit == false
        run: npm ci
      - name: Update Node.js
        uses: branoholy/update-files-action@develop
        with:
          token: ${{ secrets.BRANOHOLY_BOT_TOKEN }}
          commands: npm run node-versions-update && npm i
          paths: '.nvmrc, package.json, package-lock.json'
          branch: deps-update-node
          commit-message: 'DEPS: Update Node.js'
          commit-token: ${{ secrets.GITHUB_TOKEN }}
          body: |-
            Automatic update of Node.js versions.

            Run `npm run node-versions-update` to update Node.js versions in workflow files.

            You can use the following commands to update, commit, and push the workflow files.

            ```text
            npm run node-versions-update
            git add .github/workflows/
            git commit -m "DEPS: Update Node.js in workflow files"
            git push
            ```
          labels: dependencies
          reviewers: branoholy
